name: .NET Build

on:
  pull_request:
  push:
    branches: [ "main" ]
    paths:
      - '*'
      - '!/readme.md'
      - '!/SECURITY.md'
      - '!/licence.txt'
      - '!/Benchmark/*'
      - '!/IntegrationTest/*'
      - '!/dists/*'
      - '!/assets/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/UnitTests/BCrypt.Net.UnitTests.csproj
    - name: Build
      run: dotnet build --no-restore src/UnitTests/BCrypt.Net.UnitTests.csproj -c Release /p:CI=true
    - name: Test
      run: dotnet test --no-build --verbosity normal src/UnitTests/BCrypt.Net.UnitTests.csproj -c Release --logger GitHubActions /p:CI=true