name: Infer#

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'

permissions:
  contents: read
  security-events: write

env:
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  infersharp:
    name: Infer# Analysis
    runs-on: ubuntu-24.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: 8.x

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: 10.x

    - name: Build
      run: dotnet build src/BCrypt.Net/BCrypt.Net.csproj --configuration Release --framework net8.0

    - name: Run Infer#
      uses: microsoft/infersharpaction@b749060de518f410f92c87d37d2366e5e9d7c5fc #v1.5
      id: runinfersharp
      with:
        binary-path: src/BCrypt.Net/bin/Release/net8.0

    - name: Upload SARIF to GitHub Security
      uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
      with:
        sarif_file: infer-out/report.sarif
