name: Infer#

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'

permissions:
  contents: read
  security-events: write

env:
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  infersharp:
    name: Infer# Analysis
    runs-on: ubuntu-24.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
      with:
        dotnet-version: 10.0.x

    - name: Build
      run: dotnet build src/BCrypt.Net/BCrypt.Net.csproj --configuration Release --framework net8.0

    - name: Run Infer#
      uses: microsoft/infersharpaction@v1.5
      id: runinfersharp
      with:
        binary-path: src/BCrypt.Net/bin/Release/net8.0

    - name: Upload SARIF to GitHub Security
      uses: github/codeql-action/upload-sarif@d3678e237b9c32a6c9bffb3315c335f976f3549f # v3.30.2
      with:
        sarif_file: infer-out/report.sarif
