name: Markdown Links Check

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**.md'
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
  #schedule:
  # Run every-day at 9:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
  #- cron: "0 9 * * *"
permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'Check for dead links in markdown files'
        uses: gaurav-nelson/github-action-markdown-link-check@1b916f2cf6c36510a6059943104e3c42ce6c16bc # 1.0.16
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
