name: Add code coverage summary to PRs

# Allows code coverage comments to be embedded in PRs if the build was run on a fork.

on:
  workflow_run:
    workflows: [ "ci-build" ]
    types:
      - completed

jobs:
  prCoverageComment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if:
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: 'Download coverage results'
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: coverage-results

      - name: Add Code Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
